#!/bin/bash
#
# CMHelper: Starts the CMHelper
#
# chkconfig:   345 80 02
# description: ... \
#              ...
# processname: CMHelper

### BEGIN INIT INFO
# Provides:          cmhelper
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $syslog
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Starts the CM Helper
# Description:       
#                    
### END INIT INFO

CMHELPER_SCRIPT=/opt/CMClient/CMHelper-service.sh

# Source function library.
if [ -r /etc/init.d/functions ]; then
  . /etc/init.d/functions
elif [ -r /lib/lsb/init-functions ]; then
  . /lib/lsb/init-functions
else
  echo "Unsupported!"
  exit -1
fi

RETVAL=0

base=${0##*/}

start() {
	echo -n $"Starting CMHelper ... "
	su - cmhelper -c "$CMHELPER_SCRIPT start"
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	echo -n $"Shutting down CMHelper: "
	ps -ef | grep "\<CMHelper\>" | grep -v "grep" > /dev/null 2> /dev/null
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
               su - cmhelper -c "$CMHELPER_SCRIPT stop"
	       RETVAL=$?

        else
               RETVAL=0; 
        fi
	return $RETVAL
}

status() {
	echo -n $"CMHelper status: "
	ps -ef | grep "\<CMHelper\>" | grep -v "grep" > /dev/null 2> /dev/null
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
		echo "running"
	else
		echo "stopped"
		RETVAL=3
	fi
	return $RETVAL
}

restart() {
	stop
	start
}

RETVAL=0

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status
        RETVAL=$?
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 2
        ;;
esac

exit $RETVAL
